spring.application.name=customer

spring.datasource.url=jdbc:postgresql://localhost:5432/enterprisedb
spring.datasource.username=postgres
spring.datasource.password=postgres

# Critical: Turn off Hibernate auto-DDL in production architectures!
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway Configuration
spring.flyway.enabled=true # false in production
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration